// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using X39.Software.ExamMaker.Api.Storage.Exam;

#nullable disable

namespace X39.Software.ExamMaker.Api.Storage.Exam.Migrations
{
    [DbContext(typeof(ExamDbContext))]
    [Migration("20251222132331_Things")]
    partial class Things
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<long>("RolesId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsersId")
                        .HasColumnType("bigint");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.Exam", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Identifier")
                        .HasColumnType("uuid");

                    b.Property<long>("OrganizationFk")
                        .HasColumnType("bigint");

                    b.Property<string>("Preamble")
                        .IsRequired()
                        .HasMaxLength(4095)
                        .HasColumnType("character varying(4095)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.HasIndex("OrganizationFk");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.ExamAnswer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(4095)
                        .HasColumnType("character varying(4095)");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExamQuestionFk")
                        .HasColumnType("bigint");

                    b.Property<Guid>("Identifier")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<long>("OrganizationFk")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .HasMaxLength(4095)
                        .HasColumnType("character varying(4095)");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExamQuestionFk");

                    b.HasIndex("OrganizationFk");

                    b.ToTable("ExamAnswers");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.ExamQuestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("CorrectAnswersToTake")
                        .HasColumnType("integer");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExamTopicFk")
                        .HasColumnType("bigint");

                    b.Property<Guid>("Identifier")
                        .HasColumnType("uuid");

                    b.Property<int?>("IncorrectAnswersToTake")
                        .HasColumnType("integer");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<long>("OrganizationFk")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExamTopicFk");

                    b.HasIndex("OrganizationFk");

                    b.ToTable("ExamQuestions");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.ExamTopic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExamFk")
                        .HasColumnType("bigint");

                    b.Property<Guid>("Identifier")
                        .HasColumnType("uuid");

                    b.Property<long>("OrganizationFk")
                        .HasColumnType("bigint");

                    b.Property<int?>("QuestionAmountToTake")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExamFk");

                    b.HasIndex("OrganizationFk");

                    b.ToTable("ExamTopics");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.Organization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.OrganizationRegistrationToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedByFk")
                        .HasColumnType("bigint");

                    b.Property<Instant>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("OrganizationFk")
                        .HasColumnType("bigint");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(340)
                        .HasColumnType("character varying(340)");

                    b.Property<Instant?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UsedByFk")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByFk");

                    b.HasIndex("OrganizationFk");

                    b.HasIndex("UsedByFk");

                    b.ToTable("OrganizationRegistrationTokens");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsInternalRole")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Identifier = "Administrators",
                            IsInternalRole = true,
                            Title = "Administrators"
                        });
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("OrganizationFk")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationFk");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.UserToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(88)
                        .HasColumnType("character varying(88)");

                    b.Property<Instant>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserFk")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserFk");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("X39.Software.ExamMaker.Api.Storage.Exam.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("X39.Software.ExamMaker.Api.Storage.Exam.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.Exam", b =>
                {
                    b.HasOne("X39.Software.ExamMaker.Api.Storage.Exam.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.ExamAnswer", b =>
                {
                    b.HasOne("X39.Software.ExamMaker.Api.Storage.Exam.Entities.ExamQuestion", "ExamQuestion")
                        .WithMany("ExamAnswers")
                        .HasForeignKey("ExamQuestionFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("X39.Software.ExamMaker.Api.Storage.Exam.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamQuestion");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.ExamQuestion", b =>
                {
                    b.HasOne("X39.Software.ExamMaker.Api.Storage.Exam.Entities.ExamTopic", "ExamTopic")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("ExamTopicFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("X39.Software.ExamMaker.Api.Storage.Exam.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamTopic");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.ExamTopic", b =>
                {
                    b.HasOne("X39.Software.ExamMaker.Api.Storage.Exam.Entities.Exam", "Exam")
                        .WithMany("ExamTopics")
                        .HasForeignKey("ExamFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("X39.Software.ExamMaker.Api.Storage.Exam.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.OrganizationRegistrationToken", b =>
                {
                    b.HasOne("X39.Software.ExamMaker.Api.Storage.Exam.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("X39.Software.ExamMaker.Api.Storage.Exam.Entities.Organization", "Organization")
                        .WithMany("RegistrationTokens")
                        .HasForeignKey("OrganizationFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("X39.Software.ExamMaker.Api.Storage.Exam.Entities.User", "UsedBy")
                        .WithMany()
                        .HasForeignKey("UsedByFk");

                    b.Navigation("CreatedBy");

                    b.Navigation("Organization");

                    b.Navigation("UsedBy");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.User", b =>
                {
                    b.HasOne("X39.Software.ExamMaker.Api.Storage.Exam.Entities.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.UserToken", b =>
                {
                    b.HasOne("X39.Software.ExamMaker.Api.Storage.Exam.Entities.User", "User")
                        .WithMany("UserTokens")
                        .HasForeignKey("UserFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.Exam", b =>
                {
                    b.Navigation("ExamTopics");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.ExamQuestion", b =>
                {
                    b.Navigation("ExamAnswers");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.ExamTopic", b =>
                {
                    b.Navigation("ExamQuestions");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.Organization", b =>
                {
                    b.Navigation("RegistrationTokens");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.User", b =>
                {
                    b.Navigation("UserTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
