// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using X39.Software.ExamMaker.Api.Storage.Exam;

#nullable disable

namespace X39.Software.ExamMaker.Api.Storage.Exam.Migrations
{
    [DbContext(typeof(ExamDbContext))]
    partial class ExamDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.Exam", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Identifier")
                        .HasColumnType("uuid");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Preamble")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.ExamAnswer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExamQuestionId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("Identifier")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExamQuestionId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("ExamAnswers");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.ExamQuestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("CorrectAnswersToTake")
                        .HasColumnType("integer");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExamTopicId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("Identifier")
                        .HasColumnType("uuid");

                    b.Property<int?>("IncorrectAnswersToTake")
                        .HasColumnType("integer");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExamTopicId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("ExamQuestions");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.ExamTopic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExamId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("Identifier")
                        .HasColumnType("uuid");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<int?>("QuestionAmountToTake")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("ExamTopics");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.Organization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.OrganizationRegistrationToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<Instant>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Instant?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UsedById")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UsedById");

                    b.ToTable("OrganizationRegistrationTokens");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.UserToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.Exam", b =>
                {
                    b.HasOne("X39.Software.ExamMaker.Api.Storage.Exam.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.ExamAnswer", b =>
                {
                    b.HasOne("X39.Software.ExamMaker.Api.Storage.Exam.Entities.ExamQuestion", "ExamQuestion")
                        .WithMany("ExamAnswers")
                        .HasForeignKey("ExamQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("X39.Software.ExamMaker.Api.Storage.Exam.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamQuestion");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.ExamQuestion", b =>
                {
                    b.HasOne("X39.Software.ExamMaker.Api.Storage.Exam.Entities.ExamTopic", "ExamTopic")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("ExamTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("X39.Software.ExamMaker.Api.Storage.Exam.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamTopic");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.ExamTopic", b =>
                {
                    b.HasOne("X39.Software.ExamMaker.Api.Storage.Exam.Entities.Exam", "Exam")
                        .WithMany("ExamTopics")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("X39.Software.ExamMaker.Api.Storage.Exam.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.OrganizationRegistrationToken", b =>
                {
                    b.HasOne("X39.Software.ExamMaker.Api.Storage.Exam.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("X39.Software.ExamMaker.Api.Storage.Exam.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("X39.Software.ExamMaker.Api.Storage.Exam.Entities.User", "UsedBy")
                        .WithMany()
                        .HasForeignKey("UsedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("Organization");

                    b.Navigation("UsedBy");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.User", b =>
                {
                    b.HasOne("X39.Software.ExamMaker.Api.Storage.Exam.Entities.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.UserToken", b =>
                {
                    b.HasOne("X39.Software.ExamMaker.Api.Storage.Exam.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.Exam", b =>
                {
                    b.Navigation("ExamTopics");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.ExamQuestion", b =>
                {
                    b.Navigation("ExamAnswers");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.ExamTopic", b =>
                {
                    b.Navigation("ExamQuestions");
                });

            modelBuilder.Entity("X39.Software.ExamMaker.Api.Storage.Exam.Entities.Organization", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
