// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using X39.Software.ExamMaker.Users.CreateRegistrationLink;
using X39.Software.ExamMaker.Users.Login;
using X39.Software.ExamMaker.Users.Logout;
using X39.Software.ExamMaker.Users.Refresh;
using X39.Software.ExamMaker.Users.Register;
namespace X39.Software.ExamMaker.Users
{
    /// <summary>
    /// Builds and executes requests for operations under \Users
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UsersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The createRegistrationLink property</summary>
        public global::X39.Software.ExamMaker.Users.CreateRegistrationLink.CreateRegistrationLinkRequestBuilder CreateRegistrationLink
        {
            get => new global::X39.Software.ExamMaker.Users.CreateRegistrationLink.CreateRegistrationLinkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The login property</summary>
        public global::X39.Software.ExamMaker.Users.Login.LoginRequestBuilder Login
        {
            get => new global::X39.Software.ExamMaker.Users.Login.LoginRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The logout property</summary>
        public global::X39.Software.ExamMaker.Users.Logout.LogoutRequestBuilder Logout
        {
            get => new global::X39.Software.ExamMaker.Users.Logout.LogoutRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The refresh property</summary>
        public global::X39.Software.ExamMaker.Users.Refresh.RefreshRequestBuilder Refresh
        {
            get => new global::X39.Software.ExamMaker.Users.Refresh.RefreshRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The register property</summary>
        public global::X39.Software.ExamMaker.Users.Register.RegisterRequestBuilder Register
        {
            get => new global::X39.Software.ExamMaker.Users.Register.RegisterRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.Software.ExamMaker.Users.UsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Users", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.Software.ExamMaker.Users.UsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Users", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
