// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using X39.Software.ExamMaker.Users.Register.Organization;
using X39.Software.ExamMaker.Users.Register.User;
namespace X39.Software.ExamMaker.Users.Register
{
    /// <summary>
    /// Builds and executes requests for operations under \Users\register
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RegisterRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The organization property</summary>
        public global::X39.Software.ExamMaker.Users.Register.Organization.OrganizationRequestBuilder Organization
        {
            get => new global::X39.Software.ExamMaker.Users.Register.Organization.OrganizationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The user property</summary>
        public global::X39.Software.ExamMaker.Users.Register.User.UserRequestBuilder User
        {
            get => new global::X39.Software.ExamMaker.Users.Register.User.UserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.Software.ExamMaker.Users.Register.RegisterRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RegisterRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Users/register", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.Software.ExamMaker.Users.Register.RegisterRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RegisterRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Users/register", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
