// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using X39.Software.ExamMaker.Exam.Item.Topic.Item.Delete;
using X39.Software.ExamMaker.Exam.Item.Topic.Item.Emplace;
using X39.Software.ExamMaker.Exam.Item.Topic.Item.Question;
namespace X39.Software.ExamMaker.Exam.Item.Topic.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \exam\{examId}\topic\{topicId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithTopicItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The deletePath property</summary>
        public global::X39.Software.ExamMaker.Exam.Item.Topic.Item.Delete.DeleteRequestBuilder DeletePath
        {
            get => new global::X39.Software.ExamMaker.Exam.Item.Topic.Item.Delete.DeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The emplace property</summary>
        public global::X39.Software.ExamMaker.Exam.Item.Topic.Item.Emplace.EmplaceRequestBuilder Emplace
        {
            get => new global::X39.Software.ExamMaker.Exam.Item.Topic.Item.Emplace.EmplaceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The question property</summary>
        public global::X39.Software.ExamMaker.Exam.Item.Topic.Item.Question.QuestionRequestBuilder Question
        {
            get => new global::X39.Software.ExamMaker.Exam.Item.Topic.Item.Question.QuestionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.Software.ExamMaker.Exam.Item.Topic.Item.WithTopicItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTopicItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/exam/{examId}/topic/{topicId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.Software.ExamMaker.Exam.Item.Topic.Item.WithTopicItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTopicItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/exam/{examId}/topic/{topicId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
