//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X39.Software.ExamMaker.WebApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("X39.Software.ExamMaker.WebApp.Properties.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprint.
        /// </summary>
        internal static string Layout_MainLayout_Footer_Imprint {
            get {
                return ResourceManager.GetString("Layout_MainLayout_Footer_Imprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string Layout_MainLayout_Header_Login {
            get {
                return ResourceManager.GetString("Layout_MainLayout_Header_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        internal static string Layout_MainLayout_Header_Profile_Logout {
            get {
                return ResourceManager.GetString("Layout_MainLayout_Header_Profile_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Layout_MainLayout_Header_Profile_ViewAccountConfiguration {
            get {
                return ResourceManager.GetString("Layout_MainLayout_Header_Profile_ViewAccountConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExamMaker.
        /// </summary>
        internal static string Layout_MainLayout_PageTitle {
            get {
                return ResourceManager.GetString("Layout_MainLayout_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input E-Mail address.
        /// </summary>
        internal static string Pages_Authentication_Login_Card_EMailAria {
            get {
                return ResourceManager.GetString("Pages_Authentication_Login_Card_EMailAria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        internal static string Pages_Authentication_Login_Card_EMailLabel {
            get {
                return ResourceManager.GetString("Pages_Authentication_Login_Card_EMailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string Pages_Authentication_Login_Card_LoginButton {
            get {
                return ResourceManager.GetString("Pages_Authentication_Login_Card_LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string Pages_Authentication_Login_Card_LoginSubject {
            get {
                return ResourceManager.GetString("Pages_Authentication_Login_Card_LoginSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input the password.
        /// </summary>
        internal static string Pages_Authentication_Login_Card_PasswordAria {
            get {
                return ResourceManager.GetString("Pages_Authentication_Login_Card_PasswordAria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Pages_Authentication_Login_Card_PasswordLabel {
            get {
                return ResourceManager.GetString("Pages_Authentication_Login_Card_PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register instead.
        /// </summary>
        internal static string Pages_Authentication_Login_Card_ToRegistrationButton {
            get {
                return ResourceManager.GetString("Pages_Authentication_Login_Card_ToRegistrationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in.
        /// </summary>
        internal static string Pages_Authentication_Login_Toast_LoggingIn {
            get {
                return ResourceManager.GetString("Pages_Authentication_Login_Toast_LoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed.
        /// </summary>
        internal static string Pages_Authentication_Login_Toast_LoginFailed {
            get {
                return ResourceManager.GetString("Pages_Authentication_Login_Toast_LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Successful.
        /// </summary>
        internal static string Pages_Authentication_Login_Toast_LoginSuccessful {
            get {
                return ResourceManager.GetString("Pages_Authentication_Login_Toast_LoginSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input E-Mail address.
        /// </summary>
        internal static string Pages_Authentication_Register_Card_EMailAria {
            get {
                return ResourceManager.GetString("Pages_Authentication_Register_Card_EMailAria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        internal static string Pages_Authentication_Register_Card_EMailLabel {
            get {
                return ResourceManager.GetString("Pages_Authentication_Register_Card_EMailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input first name.
        /// </summary>
        internal static string Pages_Authentication_Register_Card_FirstNameAria {
            get {
                return ResourceManager.GetString("Pages_Authentication_Register_Card_FirstNameAria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string Pages_Authentication_Register_Card_FirstNameLabel {
            get {
                return ResourceManager.GetString("Pages_Authentication_Register_Card_FirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input last name.
        /// </summary>
        internal static string Pages_Authentication_Register_Card_LastNameAria {
            get {
                return ResourceManager.GetString("Pages_Authentication_Register_Card_LastNameAria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string Pages_Authentication_Register_Card_LastNameLabel {
            get {
                return ResourceManager.GetString("Pages_Authentication_Register_Card_LastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input organization name.
        /// </summary>
        internal static string Pages_Authentication_Register_Card_OrganizationNameAria {
            get {
                return ResourceManager.GetString("Pages_Authentication_Register_Card_OrganizationNameAria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Name.
        /// </summary>
        internal static string Pages_Authentication_Register_Card_OrganizationNameLabel {
            get {
                return ResourceManager.GetString("Pages_Authentication_Register_Card_OrganizationNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input the password.
        /// </summary>
        internal static string Pages_Authentication_Register_Card_PasswordAria {
            get {
                return ResourceManager.GetString("Pages_Authentication_Register_Card_PasswordAria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Pages_Authentication_Register_Card_PasswordLabel {
            get {
                return ResourceManager.GetString("Pages_Authentication_Register_Card_PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Pages_Authentication_Register_Card_RegisterButton {
            get {
                return ResourceManager.GetString("Pages_Authentication_Register_Card_RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string Pages_Authentication_Register_Card_RegisterSubject {
            get {
                return ResourceManager.GetString("Pages_Authentication_Register_Card_RegisterSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login instead.
        /// </summary>
        internal static string Pages_Authentication_Register_Card_ToLoginButton {
            get {
                return ResourceManager.GetString("Pages_Authentication_Register_Card_ToLoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register user instead.
        /// </summary>
        internal static string Pages_Authentication_Register_Card_ToTokenRegistrationButton {
            get {
                return ResourceManager.GetString("Pages_Authentication_Register_Card_ToTokenRegistrationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input E-Mail address.
        /// </summary>
        internal static string Pages_Authentication_RegisterUser_Card_EMailAria {
            get {
                return ResourceManager.GetString("Pages_Authentication_RegisterUser_Card_EMailAria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        internal static string Pages_Authentication_RegisterUser_Card_EMailLabel {
            get {
                return ResourceManager.GetString("Pages_Authentication_RegisterUser_Card_EMailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input first name.
        /// </summary>
        internal static string Pages_Authentication_RegisterUser_Card_FirstNameAria {
            get {
                return ResourceManager.GetString("Pages_Authentication_RegisterUser_Card_FirstNameAria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string Pages_Authentication_RegisterUser_Card_FirstNameLabel {
            get {
                return ResourceManager.GetString("Pages_Authentication_RegisterUser_Card_FirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input last name.
        /// </summary>
        internal static string Pages_Authentication_RegisterUser_Card_LastNameAria {
            get {
                return ResourceManager.GetString("Pages_Authentication_RegisterUser_Card_LastNameAria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string Pages_Authentication_RegisterUser_Card_LastNameLabel {
            get {
                return ResourceManager.GetString("Pages_Authentication_RegisterUser_Card_LastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input the password.
        /// </summary>
        internal static string Pages_Authentication_RegisterUser_Card_PasswordAria {
            get {
                return ResourceManager.GetString("Pages_Authentication_RegisterUser_Card_PasswordAria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Pages_Authentication_RegisterUser_Card_PasswordLabel {
            get {
                return ResourceManager.GetString("Pages_Authentication_RegisterUser_Card_PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Pages_Authentication_RegisterUser_Card_RegisterButton {
            get {
                return ResourceManager.GetString("Pages_Authentication_RegisterUser_Card_RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string Pages_Authentication_RegisterUser_Card_RegisterSubject {
            get {
                return ResourceManager.GetString("Pages_Authentication_RegisterUser_Card_RegisterSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login instead.
        /// </summary>
        internal static string Pages_Authentication_RegisterUser_Card_ToLoginButton {
            get {
                return ResourceManager.GetString("Pages_Authentication_RegisterUser_Card_ToLoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register user instead.
        /// </summary>
        internal static string Pages_Authentication_RegisterUser_Card_ToTokenRegistrationButton {
            get {
                return ResourceManager.GetString("Pages_Authentication_RegisterUser_Card_ToTokenRegistrationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprint.
        /// </summary>
        internal static string Pages_Imprint_Imprint {
            get {
                return ResourceManager.GetString("Pages_Imprint_Imprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created at.
        /// </summary>
        internal static string Pages_Management_Exams_All_Index_GridHeaders_CreatedAt {
            get {
                return ResourceManager.GetString("Pages_Management_Exams_All_Index_GridHeaders_CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        internal static string Pages_Management_Exams_All_Index_GridHeaders_Identifier {
            get {
                return ResourceManager.GetString("Pages_Management_Exams_All_Index_GridHeaders_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        internal static string Pages_Management_Exams_All_Index_GridHeaders_Operations {
            get {
                return ResourceManager.GetString("Pages_Management_Exams_All_Index_GridHeaders_Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Pages_Management_Exams_All_Index_GridHeaders_Title {
            get {
                return ResourceManager.GetString("Pages_Management_Exams_All_Index_GridHeaders_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Pages_Management_Exams_All_Index_GridOperation_OpenExam {
            get {
                return ResourceManager.GetString("Pages_Management_Exams_All_Index_GridOperation_OpenExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Exam.
        /// </summary>
        internal static string Pages_Management_Exams_All_Index_ToolBar_CreateAndOpenNewExam {
            get {
                return ResourceManager.GetString("Pages_Management_Exams_All_Index_ToolBar_CreateAndOpenNewExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Answer.
        /// </summary>
        internal static string Pages_Management_Exams_Arg_Button_AddAnswer {
            get {
                return ResourceManager.GetString("Pages_Management_Exams_Arg_Button_AddAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Question.
        /// </summary>
        internal static string Pages_Management_Exams_Arg_Button_AddQuestion {
            get {
                return ResourceManager.GetString("Pages_Management_Exams_Arg_Button_AddQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Topic.
        /// </summary>
        internal static string Pages_Management_Exams_Arg_Button_AddTopic {
            get {
                return ResourceManager.GetString("Pages_Management_Exams_Arg_Button_AddTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Answer.
        /// </summary>
        internal static string Pages_Management_Exams_Arg_Button_DeleteAnswer {
            get {
                return ResourceManager.GetString("Pages_Management_Exams_Arg_Button_DeleteAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Question.
        /// </summary>
        internal static string Pages_Management_Exams_Arg_Button_DeleteQuestion {
            get {
                return ResourceManager.GetString("Pages_Management_Exams_Arg_Button_DeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Topic.
        /// </summary>
        internal static string Pages_Management_Exams_Arg_Button_DeleteTopic {
            get {
                return ResourceManager.GetString("Pages_Management_Exams_Arg_Button_DeleteTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        internal static string Pages_Management_Exams_Arg_Label_Answer {
            get {
                return ResourceManager.GetString("Pages_Management_Exams_Arg_Label_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string Pages_Management_Exams_Arg_Label_AnswerReason {
            get {
                return ResourceManager.GetString("Pages_Management_Exams_Arg_Label_AnswerReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct Answers to Take.
        /// </summary>
        internal static string Pages_Management_Exams_Arg_Label_CorrectAnswersToTake {
            get {
                return ResourceManager.GetString("Pages_Management_Exams_Arg_Label_CorrectAnswersToTake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preamble.
        /// </summary>
        internal static string Pages_Management_Exams_Arg_Label_ExamPreamble {
            get {
                return ResourceManager.GetString("Pages_Management_Exams_Arg_Label_ExamPreamble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Pages_Management_Exams_Arg_Label_ExamTitle {
            get {
                return ResourceManager.GetString("Pages_Management_Exams_Arg_Label_ExamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Answers to Take.
        /// </summary>
        internal static string Pages_Management_Exams_Arg_Label_IncorrectAnswersToTake {
            get {
                return ResourceManager.GetString("Pages_Management_Exams_Arg_Label_IncorrectAnswersToTake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Correct.
        /// </summary>
        internal static string Pages_Management_Exams_Arg_Label_IsCorrect {
            get {
                return ResourceManager.GetString("Pages_Management_Exams_Arg_Label_IsCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions to Take.
        /// </summary>
        internal static string Pages_Management_Exams_Arg_Label_QuestionAmountToTake {
            get {
                return ResourceManager.GetString("Pages_Management_Exams_Arg_Label_QuestionAmountToTake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Kind.
        /// </summary>
        internal static string Pages_Management_Exams_Arg_Label_QuestionKind {
            get {
                return ResourceManager.GetString("Pages_Management_Exams_Arg_Label_QuestionKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Title.
        /// </summary>
        internal static string Pages_Management_Exams_Arg_Label_QuestionTitle {
            get {
                return ResourceManager.GetString("Pages_Management_Exams_Arg_Label_QuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic Title.
        /// </summary>
        internal static string Pages_Management_Exams_Arg_Label_TopicTitle {
            get {
                return ResourceManager.GetString("Pages_Management_Exams_Arg_Label_TopicTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preamble.
        /// </summary>
        internal static string Pages_Management_Exams_Arg_Placeholder_ExamPreamble {
            get {
                return ResourceManager.GetString("Pages_Management_Exams_Arg_Placeholder_ExamPreamble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Pages_Management_Exams_Arg_Placeholder_ExamTitle {
            get {
                return ResourceManager.GetString("Pages_Management_Exams_Arg_Placeholder_ExamTitle", resourceCulture);
            }
        }
    }
}
