// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using X39.Software.ExamMaker.Exam.Item.Topic.Item.Question.Item.Answer.All;
using X39.Software.ExamMaker.Exam.Item.Topic.Item.Question.Item.Answer.Item;
namespace X39.Software.ExamMaker.Exam.Item.Topic.Item.Question.Item.Answer
{
    /// <summary>
    /// Builds and executes requests for operations under \exam\{examId}\topic\{topicId}\question\{questionId}\answer
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AnswerRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The all property</summary>
        public global::X39.Software.ExamMaker.Exam.Item.Topic.Item.Question.Item.Answer.All.AllRequestBuilder All
        {
            get => new global::X39.Software.ExamMaker.Exam.Item.Topic.Item.Question.Item.Answer.All.AllRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the X39.Software.ExamMaker.exam.item.topic.item.question.item.answer.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::X39.Software.ExamMaker.Exam.Item.Topic.Item.Question.Item.Answer.Item.WithAnswerItemRequestBuilder"/></returns>
        public global::X39.Software.ExamMaker.Exam.Item.Topic.Item.Question.Item.Answer.Item.WithAnswerItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("answerId", position);
                return new global::X39.Software.ExamMaker.Exam.Item.Topic.Item.Question.Item.Answer.Item.WithAnswerItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the X39.Software.ExamMaker.exam.item.topic.item.question.item.answer.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::X39.Software.ExamMaker.Exam.Item.Topic.Item.Question.Item.Answer.Item.WithAnswerItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::X39.Software.ExamMaker.Exam.Item.Topic.Item.Question.Item.Answer.Item.WithAnswerItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("answerId", position);
                return new global::X39.Software.ExamMaker.Exam.Item.Topic.Item.Question.Item.Answer.Item.WithAnswerItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.Software.ExamMaker.Exam.Item.Topic.Item.Question.Item.Answer.AnswerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AnswerRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/exam/{examId}/topic/{topicId}/question/{questionId}/answer", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.Software.ExamMaker.Exam.Item.Topic.Item.Question.Item.Answer.AnswerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AnswerRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/exam/{examId}/topic/{topicId}/question/{questionId}/answer", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
