// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace X39.Software.ExamMaker.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum EQuestionKind
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "MultipleChoice")]
        #pragma warning disable CS1591
        MultipleChoice,
        #pragma warning restore CS1591
        [EnumMember(Value = "FreeText")]
        #pragma warning disable CS1591
        FreeText,
        #pragma warning restore CS1591
    }
}
