// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace X39.Software.ExamMaker.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ExamQuestionUpdateDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The correctAnswersToTake property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::X39.Software.ExamMaker.Models.UpdateValueOfint? CorrectAnswersToTake { get; set; }
#nullable restore
#else
        public global::X39.Software.ExamMaker.Models.UpdateValueOfint CorrectAnswersToTake { get; set; }
#endif
        /// <summary>The incorrectAnswersToTake property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::X39.Software.ExamMaker.Models.UpdateValueOfint? IncorrectAnswersToTake { get; set; }
#nullable restore
#else
        public global::X39.Software.ExamMaker.Models.UpdateValueOfint IncorrectAnswersToTake { get; set; }
#endif
        /// <summary>The kind property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::X39.Software.ExamMaker.Models.UpdateValueOfEQuestionKind? Kind { get; set; }
#nullable restore
#else
        public global::X39.Software.ExamMaker.Models.UpdateValueOfEQuestionKind Kind { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::X39.Software.ExamMaker.Models.UpdateValueOfstring? Title { get; set; }
#nullable restore
#else
        public global::X39.Software.ExamMaker.Models.UpdateValueOfstring Title { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::X39.Software.ExamMaker.Models.ExamQuestionUpdateDto"/> and sets the default values.
        /// </summary>
        public ExamQuestionUpdateDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::X39.Software.ExamMaker.Models.ExamQuestionUpdateDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::X39.Software.ExamMaker.Models.ExamQuestionUpdateDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::X39.Software.ExamMaker.Models.ExamQuestionUpdateDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "correctAnswersToTake", n => { CorrectAnswersToTake = n.GetObjectValue<global::X39.Software.ExamMaker.Models.UpdateValueOfint>(global::X39.Software.ExamMaker.Models.UpdateValueOfint.CreateFromDiscriminatorValue); } },
                { "incorrectAnswersToTake", n => { IncorrectAnswersToTake = n.GetObjectValue<global::X39.Software.ExamMaker.Models.UpdateValueOfint>(global::X39.Software.ExamMaker.Models.UpdateValueOfint.CreateFromDiscriminatorValue); } },
                { "kind", n => { Kind = n.GetObjectValue<global::X39.Software.ExamMaker.Models.UpdateValueOfEQuestionKind>(global::X39.Software.ExamMaker.Models.UpdateValueOfEQuestionKind.CreateFromDiscriminatorValue); } },
                { "title", n => { Title = n.GetObjectValue<global::X39.Software.ExamMaker.Models.UpdateValueOfstring>(global::X39.Software.ExamMaker.Models.UpdateValueOfstring.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::X39.Software.ExamMaker.Models.UpdateValueOfint>("correctAnswersToTake", CorrectAnswersToTake);
            writer.WriteObjectValue<global::X39.Software.ExamMaker.Models.UpdateValueOfint>("incorrectAnswersToTake", IncorrectAnswersToTake);
            writer.WriteObjectValue<global::X39.Software.ExamMaker.Models.UpdateValueOfEQuestionKind>("kind", Kind);
            writer.WriteObjectValue<global::X39.Software.ExamMaker.Models.UpdateValueOfstring>("title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
