// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace X39.Software.ExamMaker.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ExamQuestionListingDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The correctAnswersToTake property</summary>
        public int? CorrectAnswersToTake { get; set; }
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The identifier property</summary>
        public Guid? Identifier { get; set; }
        /// <summary>The incorrectAnswersToTake property</summary>
        public int? IncorrectAnswersToTake { get; set; }
        /// <summary>The kind property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::X39.Software.ExamMaker.Models.EQuestionKind2? Kind { get; set; }
#nullable restore
#else
        public global::X39.Software.ExamMaker.Models.EQuestionKind2 Kind { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::X39.Software.ExamMaker.Models.ExamQuestionListingDto"/> and sets the default values.
        /// </summary>
        public ExamQuestionListingDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::X39.Software.ExamMaker.Models.ExamQuestionListingDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::X39.Software.ExamMaker.Models.ExamQuestionListingDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::X39.Software.ExamMaker.Models.ExamQuestionListingDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "correctAnswersToTake", n => { CorrectAnswersToTake = n.GetIntValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "identifier", n => { Identifier = n.GetGuidValue(); } },
                { "incorrectAnswersToTake", n => { IncorrectAnswersToTake = n.GetIntValue(); } },
                { "kind", n => { Kind = n.GetObjectValue<global::X39.Software.ExamMaker.Models.EQuestionKind2>(global::X39.Software.ExamMaker.Models.EQuestionKind2.CreateFromDiscriminatorValue); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("correctAnswersToTake", CorrectAnswersToTake);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteGuidValue("identifier", Identifier);
            writer.WriteIntValue("incorrectAnswersToTake", IncorrectAnswersToTake);
            writer.WriteObjectValue<global::X39.Software.ExamMaker.Models.EQuestionKind2>("kind", Kind);
            writer.WriteStringValue("title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
